// DevolksCapital V1 Worker - server auth, D1 user isolation, Binance prices/candles, trades and admin simulation
const PAIRS=["BTCUSDT","ETHUSDT","SOLUSDT","BNBUSDT","XRPUSDT"];
const INTERVALS=new Set(["1m","3m","5m","15m","30m","1h","2h","4h","6h","8h","12h","1d","3d","1w","1M"]);
const ADMIN_EMAIL="devolkscapital@gmail.com";
const SESSION_DAYS=7;
export default{async fetch(request,env){const u=new URL(request.url);try{
if(request.method==="OPTIONS")return cors(new Response(null,{status:204}));
if(u.pathname==="/api/health")return json({ok:true,storage:!!env.DB});
if(u.pathname==="/api/auth/signup"&&request.method==="POST")return signup(request,env);
if(u.pathname==="/api/auth/login"&&request.method==="POST")return login(request,env);
if(u.pathname==="/api/auth/me")return me(request,env);
if(u.pathname==="/api/auth/logout")return logout();
if(u.pathname==="/api/prices")return prices(env);
if(u.pathname==="/api/klines")return klines(u);
if(u.pathname==="/api/trades")return trades(request,env);
if(u.pathname==="/api/simulation")return simulation(request,u,env);
if(u.pathname==="/api/admin/login"&&request.method==="POST")return adminLogin(request,env);
if(u.pathname==="/api/admin/me")return json({ok:true,admin:!!await admin(request,env)});
if(u.pathname==="/api/admin/logout")return json({ok:true},200,{"Set-Cookie":cookie("dc_admin","",0)});
if(u.pathname==="/api/admin/state")return adminState(request,env);
if(u.pathname==="/api/admin/trades")return adminTrades(request,env);
if(u.pathname==="/api/admin/credit"&&request.method==="POST")return adminCredit(request,env);
return env.ASSETS.fetch(request);
}catch(e){return json({ok:false,error:"Server error."},500)}}};
function json(x,s=200,h={}){return cors(new Response(JSON.stringify(x),{status:s,headers:{"Content-Type":"application/json","Cache-Control":"no-store",...h}}))}
function cors(r){let h=new Headers(r.headers);h.set("Access-Control-Allow-Origin","*");h.set("Access-Control-Allow-Headers","Content-Type");h.set("Access-Control-Allow-Methods","GET,POST,PATCH,DELETE,OPTIONS");return new Response(r.body,{status:r.status,headers:h})}
function now(){return new Date().toISOString()} function id(){return crypto.randomUUID()}
function cookie(n,v,a=604800){return `${n}=${v}; Max-Age=${a}; Path=/; HttpOnly; Secure; SameSite=Lax`}
function getCookie(r,n){let m=(r.headers.get("Cookie")||"").match(new RegExp(`(?:^|; )${n}=([^;]+)`));return m&&m[1]}
async function hash(s){let d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function b64(b){let s="";for(let x of b)s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
async function sign(p,sec){let k=await crypto.subtle.importKey("raw",new TextEncoder().encode(sec),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return b64(new Uint8Array(await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(p))))}
async function token(o,sec){let p=b64(new TextEncoder().encode(JSON.stringify(o)));return p+"."+await sign(p,sec)}
async function session(r,e,n="dc_session"){let t=getCookie(r,n);if(!t||!e.SESSION_SECRET)return null;try{let[a,b]=t.split("."),x=await sign(a,e.SESSION_SECRET);if(x!==b)return null;let raw=a.replace(/-/g,"+").replace(/_/g,"/");while(raw.length%4)raw+="=";let o=JSON.parse(atob(raw));return o.exp>Date.now()?o:null}catch{return null}}
async function signup(r,e){if(!e.DB)return json({ok:false,error:"D1 not configured"},503);let b=await r.json();let email=String(b.email||"").trim().toLowerCase(),pw=String(b.password||"");if(!email.includes("@")||pw.length<6)return json({ok:false,error:"Valid email and 6+ character password required"},400);if(email===ADMIN_EMAIL)return json({ok:false,error:"Reserved admin email"},403);if(await e.DB.prepare("SELECT id FROM users WHERE lower(email)=?").bind(email).first())return json({ok:false,error:"Account already exists"},409);let uid=id(),name=String(b.name||"Demo Trader").slice(0,80);await e.DB.prepare("INSERT INTO users(id,name,email,password_hash,balance,created_at) VALUES(?,?,?,?,?,?)").bind(uid,name,email,await hash(pw),10000,now()).run();let t=await token({role:"user",userId:uid,email,exp:Date.now()+604800000},e.SESSION_SECRET);return json({ok:true,user:{id:uid,name,email,balance:10000}},201,{"Set-Cookie":cookie("dc_session",t)})}
async function login(r,e){let b=await r.json(),email=String(b.email||"").trim().toLowerCase(),pw=String(b.password||"");if(email===ADMIN_EMAIL)return json({ok:false,error:"Use Admin login for this account"},403);let u=await e.DB.prepare("SELECT id,name,email,password_hash,balance FROM users WHERE lower(email)=?").bind(email).first();if(!u||u.password_hash!==await hash(pw))return json({ok:false,error:"Login details not found"},401);let t=await token({role:"user",userId:u.id,email:u.email,exp:Date.now()+604800000},e.SESSION_SECRET);return json({ok:true,user:{id:u.id,name:u.name,email:u.email,balance:+u.balance}},200,{"Set-Cookie":cookie("dc_session",t)})}
async function me(r,e){let s=await session(r,e);if(!s||s.role!=="user")return json({ok:true,authenticated:false});let u=await e.DB.prepare("SELECT id,name,email,balance FROM users WHERE id=?").bind(s.userId).first();return json(u?{ok:true,authenticated:true,user:{id:u.id,name:u.name,email:u.email,balance:+u.balance}}:{ok:true,authenticated:false})}
function logout(){return json({ok:true},200,{"Set-Cookie":cookie("dc_session","",0)})}
async function one(s){try{let r=await fetch(`https://data-api.binance.vision/api/v3/ticker/price?symbol=${s}`,{cf:{cacheTtl:0}});if(!r.ok)return null;return +(await r.json()).price}catch{return null}}
async function prices(e){let live={};await Promise.all(PAIRS.map(async p=>live[p]=await one(p)));let simulated={};if(e.DB){let r=await e.DB.prepare("SELECT symbol,price FROM simulation").all();for(let x of r.results||[])simulated[x.symbol]=+x.price}let out={};for(let p of PAIRS)out[p]=simulated[p]??live[p];return json({ok:true,prices:out,live,simulated})}
async function klines(u){let s=(u.searchParams.get("symbol")||"BTCUSDT").toUpperCase(),i=u.searchParams.get("interval")||"1m",l=Math.min(1000,Math.max(20,+(u.searchParams.get("limit")||150)));if(!PAIRS.includes(s)||!INTERVALS.has(i))return json({ok:false,error:"Bad symbol or interval"},400);let r=await fetch(`https://data-api.binance.vision/api/v3/klines?symbol=${s}&interval=${i}&limit=${l}`,{cf:{cacheTtl:0}});return new Response(await r.text(),{status:r.status,headers:{"Content-Type":"application/json","Cache-Control":"no-store","Access-Control-Allow-Origin":"*"}})}
async function user(r,e){let s=await session(r,e);return s&&s.role==="user"?s:null}
async function trades(r,e){let s=await user(r,e);if(!s)return json({ok:false,error:"Login required"},401);if(r.method==="GET"){let q=await e.DB.prepare("SELECT * FROM trades WHERE user_id=? ORDER BY opened_at DESC LIMIT 500").bind(s.userId).all();return json({ok:true,trades:q.results||[]})}let b=await r.json();if(r.method==="POST"){let m=+b.margin;if(!b.id||!b.pair||!["BUY","SELL"].includes(b.side)||!Number.isFinite(+b.entry)||m<=0)return json({ok:false,error:"Invalid trade"},400);let u=await e.DB.prepare("SELECT balance FROM users WHERE id=?").bind(s.userId).first();if(!u||+u.balance<m)return json({ok:false,error:"Insufficient balance"},400);await e.DB.batch([e.DB.prepare("UPDATE users SET balance=balance-? WHERE id=?").bind(m,s.userId),e.DB.prepare("INSERT INTO trades(id,user_id,pair,side,volume,leverage,margin,entry,sl,tp,pl,status,opened_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(String(b.id),s.userId,b.pair,b.side,+b.volume,+b.leverage,m,+b.entry,b.sl?+b.sl:null,b.tp?+b.tp:null,0,"OPEN",b.openedAt||now())]);return json({ok:true})}if(r.method==="PATCH"){let t=await e.DB.prepare("SELECT * FROM trades WHERE id=? AND user_id=? AND status='OPEN'").bind(b.id,s.userId).first();if(!t)return json({ok:false,error:"Trade not found"},404);let pl=+b.pl,refund=+t.margin+pl;await e.DB.batch([e.DB.prepare("UPDATE users SET balance=MAX(0,balance+?) WHERE id=?").bind(refund,s.userId),e.DB.prepare("UPDATE trades SET status='CLOSED',exit=?,pl=?,reason=?,closed_at=? WHERE id=? AND user_id=?").bind(+b.exit,pl,b.reason||"Manual close",now(),b.id,s.userId)]);return json({ok:true})}}
async function admin(r,e){let s=await session(r,e,"dc_admin");return s&&s.role==="admin"&&s.email===ADMIN_EMAIL?s:null}
async function adminLogin(r,e){let b=await r.json();if(String(b.email||"").toLowerCase()!==ADMIN_EMAIL||b.password!==e.ADMIN_PASSWORD)return json({ok:false,error:"Invalid admin credentials"},401);let t=await token({role:"admin",email:ADMIN_EMAIL,exp:Date.now()+604800000},e.SESSION_SECRET);return json({ok:true},200,{"Set-Cookie":cookie("dc_admin",t)})}
async function adminState(r,e){if(!await admin(r,e))return json({ok:false,error:"Admin required"},403);let u=await e.DB.prepare("SELECT id,name,email,balance,created_at FROM users ORDER BY created_at DESC").all(),t=await e.DB.prepare("SELECT * FROM trades ORDER BY opened_at DESC LIMIT 500").all();return json({ok:true,users:u.results||[],trades:t.results||[]})}
async function adminTrades(r,e){if(!await admin(r,e))return json({ok:false,error:"Admin required"},403);let t=await e.DB.prepare("SELECT * FROM trades ORDER BY opened_at DESC LIMIT 1000").all();return json({ok:true,trades:t.results||[]})}
async function adminCredit(r,e){if(!await admin(r,e))return json({ok:false,error:"Admin required"},403);let b=await r.json(),a=+b.amount*(b.direction==="debit"?-1:1);await e.DB.prepare("UPDATE users SET balance=MAX(0,balance+?) WHERE id=?").bind(a,b.userId).run();return json({ok:true})}
async function simulation(r,u,e){let s=(u.searchParams.get("symbol")||"BTCUSDT").replace("/","").toUpperCase();if(!PAIRS.includes(s))return json({ok:false,error:"Bad symbol"},400);if(r.method==="GET"){let x=await e.DB.prepare("SELECT price,updated_at FROM simulation WHERE symbol=?").bind(s).first();return json({ok:true,symbol:s,simulationPrice:x?+x.price:null,updatedAt:x?.updated_at||null})}if(!await admin(r,e))return json({ok:false,error:"Admin required"},403);if(r.method==="DELETE"){await e.DB.prepare("DELETE FROM simulation WHERE symbol=?").bind(s).run();return json({ok:true})}let b=await r.json(),amount=+b.amount,dir=b.direction==="down"?-1:1;if(!amount||amount<=0)return json({ok:false,error:"Invalid movement"},400);let old=await e.DB.prepare("SELECT price FROM simulation WHERE symbol=?").bind(s).first(),cur=old?+old.price:await one(s);if(!cur)return json({ok:false,error:"No market price"},503);let next=cur+dir*amount;await e.DB.prepare("INSERT INTO simulation(symbol,price,updated_at) VALUES(?,?,?) ON CONFLICT(symbol) DO UPDATE SET price=excluded.price,updated_at=excluded.updated_at").bind(s,next,now()).run();return json({ok:true,symbol:s,simulationPrice:next})}
